site_name: FINC50
repo_url: https://github.com/mgao6767/finc50
repo_name: mgao6767/finc50
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 <a href="https://mingze-gao.com">Mingze Gao</a>

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: date
      enable_creation_date: true

theme:
  name: material
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - announce.dismiss
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - navigation.prune 

extra:  
  generator: false
#   alternate:
#     - name: English
#       link: / 
#       lang: en
#     - name: 中文
#       link: /zh/
#       lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mgao6767/finc50
    - icon: fontawesome/solid/paper-plane
      link: mailto:mingze.gao@sydney.edu.au

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables


nav:
  - Welcome: index.md
