site_name: FINC50
site_url: https://mgao6767.github.io/finc50/
repo_url: https://github.com/mgao6767/finc50
repo_name: mgao6767/finc50
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 <a href="https://mingze-gao.com">Mingze Gao</a>

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

plugins:
  - search
  - charts:
      vega_theme: default
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - git-committers:
      repository: mgao6767/finc50
      branch: main

theme:
  name: material
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - announce.dismiss
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - toc.follow 
    - navigation.prune 
    - navigation.tabs
    - navigation.path
    - navigation.indexes 
    - navigation.top

extra:  
  generator: false
  alternate:
    - name: English
      link: /finc50/
      lang: en
    - name: 中文
      link: /finc50/zh/
      lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mgao6767/finc50
    - icon: fontawesome/solid/paper-plane
      link: mailto:mingze.gao@sydney.edu.au

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite

nav:
  - Home: index.md
  - Corporate Finance: 
      - corporate-finance/index.md
